version: '3.7'

services:

  exchange-service:
    image: sharshu/mmv3-currency-exc-service:0.0.1-snapshot
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network

networks:
  currency-network: